# Generated by Django 5.0.2 on 2024-02-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
