# Generated by Django 5.0.2 on 2024-02-27 22:10

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_positions_member_pos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.positions'),
        ),
        migrations.AlterField(
            model_name='positions',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True),
        ),
    ]
