# Generated by Django 5.0.2 on 2024-02-29 21:34

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_member_pos_alter_positions_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='tag', unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='members.positions'),
        ),
        migrations.AddField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='members.tagpost'),
        ),
    ]
