# Generated by Django 5.0.2 on 2024-03-01 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_tagpost_alter_member_pos_member_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('term', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='duties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memb', to='members.duties'),
        ),
    ]
