# Generated by Django 5.0.2 on 2024-03-09 20:04

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_duties_member_duties'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Сотрудники СПТ', 'verbose_name_plural': 'Сотрудники СПТ'},
        ),
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterField(
            model_name='member',
            name='duties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memb', to='members.duties', verbose_name='Исполняемая должность'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_public',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Ф.И.О'),
        ),
        migrations.AlterField(
            model_name='member',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='members.positions', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='member',
            name='rank',
            field=models.CharField(max_length=100, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reference',
            field=models.TextField(blank=True, verbose_name='Cправка-отзыв'),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='members.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='member',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
