# Generated by Django 5.0.2 on 2024-03-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_uploadfiles_alter_member_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfiles',
            old_name='files',
            new_name='file',
        ),
    ]
