# Generated by Django 5.0.2 on 2024-03-11 14:47

import autoslug.fields
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_from', models.CharField(db_index=True, max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='message_from', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время')),
                ('adress', models.CharField(max_length=150, verbose_name='Адрес')),
                ('message_from', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='message', to='fires.messagefrom', verbose_name='Сообщение от')),
                ('unitarea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unitarea', to='fires.unitarea', verbose_name='Район выезда')),
            ],
        ),
    ]
