# Generated by Django 5.0.2 on 2024-03-11 16:21

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankFire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(db_index=True, max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fire',
            name='rankfire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rankfire', to='fires.rankfire', verbose_name='Ранг пожара'),
        ),
    ]
