# Generated by Django 5.0.2 on 2024-03-11 16:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0002_rankfire_fire_rankfire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankfire',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='rank', unique=True),
        ),
    ]
