# Generated by Django 5.0.2 on 2024-03-11 21:15

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0003_alter_rankfire_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastRtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastrtp', models.CharField(db_index=True, max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='lastrtp', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fire',
            name='fire_area',
            field=models.IntegerField(blank=True, null=True, verbose_name='Площадь пожара'),
        ),
        migrations.AddField(
            model_name='fire',
            name='time_come',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время прибытия'),
        ),
        migrations.AddField(
            model_name='fire',
            name='time_elim',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время ликвидации'),
        ),
        migrations.AddField(
            model_name='fire',
            name='time_fire_hose',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время подачи ствола'),
        ),
        migrations.AddField(
            model_name='fire',
            name='time_loc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время локализации'),
        ),
        migrations.AlterField(
            model_name='fire',
            name='adress',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='fire',
            name='rtp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='fires.lastrtp', verbose_name='Последний РТП'),
        ),
    ]
