# Generated by Django 5.0.2 on 2024-03-12 19:33

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0004_lastrtp_fire_fire_area_fire_time_come_fire_time_elim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GdzsUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(db_index=True, max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='quantity', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fire',
            name='gdzsunits',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gdzsunits', to='fires.gdzsunits', verbose_name='Звенья ГДЗС'),
        ),
    ]
