# Generated by Django 5.0.2 on 2024-03-23 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0005_gdzsunits_fire_gdzsunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='rtp',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='rtp', to='fires.lastrtp', verbose_name='Последний РТП'),
        ),
    ]
