# Generated by Django 5.0.2 on 2024-04-04 09:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0006_alter_fire_rtp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fire',
            options={'verbose_name': 'Пожар', 'verbose_name_plural': 'Пожары'},
        ),
        migrations.AddField(
            model_name='fire',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='firefire', editable=False, max_length=255, populate_from='datetime', unique=True, verbose_name='слаг'),
        ),
    ]
