# Generated by Django 5.0.2 on 2024-04-04 09:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0007_alter_fire_options_fire_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='datetime', unique=True, verbose_name='слаг'),
        ),
    ]
